### ISSUE TITLE
can't compile for latest version

### ISSUE THREAD

**Issue by antoniograzioli** [Strum/Strums_Mental_VCV_Modules#1]
MentalButtons won't compile...
change lines 33-35:

```
  float button_leds[8] = {};  
  bool button_states[8] = {};
  float moment_leds[7] = {};
```

**Comment by Strum** [comment]
haven't had a problem with it at my end.

what OS?

**Comment by Strum** [comment]
i updated a few things a minute ago.

**Comment by Strum** [comment]
i'll initialise the arrays fully, that should fix it, was just lazy

**Comment by antoniograzioli** [comment]
I am on Mac

 actually you initialized:
` float button_leds[8] = {0.0};  `
and it complains

edit in:
`  float button_leds[8] = {};  `
is OK

**Comment by Strum** [comment]
i've made a few other updates as well

the background graphics now load.

i hadn't noticed the new way of loading them.

**Comment by lnikj** [comment]
Not building on 0.4 Mac 10.11.6

src/MentalButtons.cpp:32:28: error: type 'double' cannot be narrowed to 'bool'
      in initializer list [-Wc++11-narrowing]
  bool button_states[7] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0};
                           ^~~
src/MentalButtons.cpp:32:28: note: insert an explicit cast to silence this issue
  bool button_states[7] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0};
                           ^~~
                           static_cast<bool>( )
src/MentalButtons.cpp:32:32: error: type 'double' cannot be narrowed to 'bool'
      in initializer list [-Wc++11-narrowing]
  bool button_states[7] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0};
                               ^~~
src/MentalButtons.cpp:32:32: note: insert an explicit cast to silence this issue
  bool button_states[7] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0};
                               ^~~
                               static_cast<bool>( )
src/MentalButtons.cpp:32:36: error: type 'double' cannot be narrowed to 'bool'
      in initializer list [-Wc++11-narrowing]
  bool button_states[7] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0};
                                   ^~~
src/MentalButtons.cpp:32:36: note: insert an explicit cast to silence this issue
  bool button_states[7] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0};
                                   ^~~
                                   static_cast<bool>( )
src/MentalButtons.cpp:32:40: error: type 'double' cannot be narrowed to 'bool'
      in initializer list [-Wc++11-narrowing]
  bool button_states[7] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0};
                                       ^~~
src/MentalButtons.cpp:32:40: note: insert an explicit cast to silence this issue
  bool button_states[7] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0};
                                       ^~~
                                       static_cast<bool>( )
src/MentalButtons.cpp:32:44: error: type 'double' cannot be narrowed to 'bool'
      in initializer list [-Wc++11-narrowing]
  bool button_states[7] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0};
                                           ^~~
src/MentalButtons.cpp:32:44: note: insert an explicit cast to silence this issue
  bool button_states[7] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0};
                                           ^~~
                                           static_cast<bool>( )
src/MentalButtons.cpp:32:48: error: type 'double' cannot be narrowed to 'bool'
      in initializer list [-Wc++11-narrowing]
  bool button_states[7] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0};
                                               ^~~
src/MentalButtons.cpp:32:48: note: insert an explicit cast to silence this issue
  bool button_states[7] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0};
                                               ^~~
                                               static_cast<bool>( )
src/MentalButtons.cpp:32:52: error: type 'double' cannot be narrowed to 'bool'
      in initializer list [-Wc++11-narrowing]
  bool button_states[7] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0};
                                                   ^~~
src/MentalButtons.cpp:32:52: note: insert an explicit cast to silence this issue
  bool button_states[7] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0};
                                                   ^~~
                                                   static_cast<bool>( )
7 errors generated.

**Comment by Strum** [comment]
derp, sorry.

made a change, try again now

**Comment by lnikj** [comment]
Sorted! Many thanks!

**Comment by Strum** [comment]
no dramas, i'd be interested in your feedback on the modules.

background graphics are still pretty primitve but i'm more concerned about functionality at this point.

**Comment by Strum** [comment]
@lnikj , @antoniograzioli 

If either of you guys could compile the code and make an OSX binary for me I'd appreciate it, i don't have access to a Mac.

**Comment by antoniograzioli** [comment]
Hi Strum I can compile it on mac (I already did, in fact) but now I am at work...maybe tonight or tomorow...

**Comment by lnikj** [comment]
I can probably give you a binary in a couple of hours.

**Comment by lnikj** [comment]
Strum

Assuming your source hasn’t changed here is one from the 14th.

[plugin.dylib.zip](https://github.com/Strum/Strums_Mental_VCV_Modules/files/1388461/plugin.dylib.zip)

I haven’t time to check at the moment but if it has changed let me know and I’ll recompile later tonight.

Best

Nik

**Comment by lnikj** [comment]
Here’s a freshly compiled one:

**Comment by Strum** [comment]
@lnikj, I'm making changes pretty much daily at the moment though I expect that will slow down in a week or so. There is no link to a file in your post and I've made significant changes since the 14th.

I've got a few little things to tidy up but with the other 3rd party modules pretty much all of what I need to do what I want to do with Rack is now available.

 @antoniograzioli, I'm loving your drum modules, thanks. Also, you might want to have a look at my clock divider code, I based it on yours but simplified the logic, added odd numbered outputs and reformatted the code to make it smaller and easier to read. I'm thinking of rewriting it using an arrays and loops for the counters rather than individual variables, it would make the code much smaller and it would easier to modify the functionality of each output, I'd thought of adding a rotate function similar to the 4ms rotating clock divider that lots of modular guys seem to use a lot.

**Comment by Strum** [comment]
I've just added a cartesian sequencer like the make noise rene to the plugin so you will certainly need to recompile now.

**Comment by Strum** [comment]
hmmm, push keeps failing, upload speed is about 3 kbps

god the internet sucks in this dumb country

**Comment by Strum** [comment]
finally after about 10 tries the push finished and the new windows binaries with the cartesian sequencer are up.

3k upload speed in 2017 in a first world country, WTF?
