### ISSUE TITLE
Strategy on API changes

### ISSUE THREAD

**Issue by Strum** [Strum/Strums_Mental_VCV_Modules#11]
The gSampleRate API change brings up the wider issue of how module developers handle API changes.

Having thought a bit about it I've decided my approach will be 1. Code API changes in to the code but comment them out until they are applied in the release version of rack. 2. Try and keep the binary releases so they work against the current Rack release. This will mean people who want to use the dev version of rack will need to build the plugin from source and comment out and in the appropriate lines to suite any API changes from the release version.

At some point in the future I will learn how to do versioning of the code and releases in a better way but hopefully this will work for now.

Hopefully I can keep the Linux and Mac Build current with the latest Rack release and the latest update to the plugins so non coders can just use it, coders shouldn't have too much trouble coping with the commenting in and out bits until i get proper versioning sorted.

**Comment by metaphorz** [comment]
@Strum: sounds good to me. I just wanted to resurface the following issue which may have gotten lost in the shuffle. However, if this is old news, please ignore this message.

The reason I was prompted to do a build of the source was that the linked 0.4.0 "Mac binary 2nd attempt" dylib does not work with 0.4.0 which can be downloaded from VCV-Rack. My earlier tests of patches that use the Mental modules were unsuccessful. I took your plugin.dylib and inserted into the WIndows distribution (which has the user interface subdirectory [res]). This yielded a directory I labeled Strums_Mental_VCV_Modules containing a file plugin.dylib (that you uploaded as a 2nd attempt) and the folder "res" needed presumably for the user interface.

**Comment by Strum** [comment]
I don't have a Mac so can't make or test the Mac releases. Others are making them I'm just adding them.

Sorry, join in on the Mac build threads and the others in there will keep you informed about Mac build issues.

**Comment by metaphorz** [comment]
Understood. Maybe I'll compiled the 0.4.0 source myself on the Mac and see what I get. A bit new to git myself too.

Just tried this and it appears to have downloaded

git clone --branch v0.4.0 https://github.com/VCVRack/Rack.git Rack-0.4.0

I'll build and let everyone know if it works
