### ISSUE TITLE
make errors in arch linux 

### ISSUE THREAD

**Issue by Malifick** [Strum/Strums_Mental_VCV_Modules#15]
Strums_Mental_VCV_Modules]$ make
g++ -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/MentalKnobs.cpp.o src/MentalKnobs.cpp
src/MentalKnobs.cpp:50:7: warning: ‘virtual void MentalKnobs::step()’ can be marked override [-Wsuggest-override]
  void step();
       ^~~~
src/MentalKnobs.cpp:112:8: warning: ‘virtual void NumberDisplayWidget::draw(NVGcontext*)’ can be marked override [-Wsuggest-override]
   void draw(NVGcontext *vg)
        ^~~~
src/MentalKnobs.cpp: In constructor ‘MentalKnobsWidget::MentalKnobsWidget()’:
src/MentalKnobs.cpp:153:26: error: ‘Davies1900hSmallBlackKnob’ was not declared in this scope
     addParam(createParam<Davies1900hSmallBlackKnob>(Vec(2, 20+group_offset*i), module, MentalKnobs::KNOB_PARAM + i, -1.0, 1.0, 0.0));
                          ^~~~~~~~~~~~~~~~~~~~~~~~~
src/MentalKnobs.cpp:153:26: note: suggested alternative: ‘_ZTIN4rack19RoundSmallBlackKnobE’
     addParam(createParam<Davies1900hSmallBlackKnob>(Vec(2, 20+group_offset*i), module, MentalKnobs::KNOB_PARAM + i, -1.0, 1.0, 0.0));
                          ^~~~~~~~~~~~~~~~~~~~~~~~~
                          _ZTIN4rack19RoundSmallBlackKnobE
src/MentalKnobs.cpp:153:131: error: no matching function for call to ‘createParam<<expression error> >(rack::Vec, MentalKnobs*&, int, double, double, double)’
 c(2, 20+group_offset*i), module, MentalKnobs::KNOB_PARAM + i, -1.0, 1.0, 0.0));
                                                                             ^
In file included from src/mental.hpp:1:0,
                 from src/MentalKnobs.cpp:10:
../../include/rack.hpp:46:14: note: candidate: template<class TParamWidget> rack::ParamWidget* rack::createParam(rack::Vec, rack::Module*, int, float, float, float)
 ParamWidget *createParam(Vec pos, Module *module, int paramId, float minValue, float maxValue, float defaultValue) {
              ^~~~~~~~~~~
../../include/rack.hpp:46:14: note:   template argument deduction/substitution failed:
src/MentalKnobs.cpp:153:131: error: template argument 1 is invalid
 c(2, 20+group_offset*i), module, MentalKnobs::KNOB_PARAM + i, -1.0, 1.0, 0.0));
                                                                             ^
src/MentalKnobs.cpp:154:132: error: no matching function for call to ‘createParam<Davies1900hSmallBlackKnob>(rack::Vec, MentalKnobs*&, int, double, double, double)’
 32, 20+group_offset*i), module, MentalKnobs::SCALE_PARAM + i,0.0, 10.0, 1.0));
                                                                            ^
In file included from src/mental.hpp:1:0,
                 from src/MentalKnobs.cpp:10:
../../include/rack.hpp:46:14: note: candidate: template<class TParamWidget> rack::ParamWidget* rack::createParam(rack::Vec, rack::Module*, int, float, float, float)
 ParamWidget *createParam(Vec pos, Module *module, int paramId, float minValue, float maxValue, float defaultValue) {
              ^~~~~~~~~~~
../../include/rack.hpp:46:14: note:   template argument deduction/substitution failed:
src/MentalKnobs.cpp:157:14: error: ‘createValueLight’ was not declared in this scope
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(10, 55+group_offset*i), &module->button_leds[0][i]));
              ^~~~~~~~~~~~~~~~
src/MentalKnobs.cpp:157:42: error: ‘GreenValueLight’ was not declared in this scope
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(10, 55+group_offset*i), &module->button_leds[0][i]));
                                          ^~~~~~~~~~~~~~~
src/MentalKnobs.cpp:157:42: error: template argument 1 is invalid
src/MentalKnobs.cpp:159:42: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(10, 80+group_offset*i), &module->button_leds[2][i]));
                                          ^~~~~~~~~~~~~~~
src/MentalKnobs.cpp:159:42: note:   expected a type, got ‘GreenValueLight’
src/MentalKnobs.cpp:161:42: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(40, 55+group_offset*i), &module->button_leds[1][i]));
                                          ^~~~~~~~~~~~~~~
src/MentalKnobs.cpp:161:42: note:   expected a type, got ‘GreenValueLight’
make: *** [../../compile.mk:54: build/src/MentalKnobs.cpp.o] Error 1

**Comment by Strum** [comment]
The errors are a result of the api changes since the last rack release.

Will try and get the code updated for the dev version this week.
