### ISSUE TITLE
Here is the new Mac zip for the plugins folder

### ISSUE THREAD

**Issue by metaphorz** [Strum/Strums_Mental_VCV_Modules#20]
[Strums_Mental_VCV_Modules_04h.zip](https://github.com/Strum/Strums_Mental_VCV_Modules/files/1464091/Strums_Mental_VCV_Modules_04h.zip)

**Comment by nay-seven** [comment]
Thanks !

**Comment by metaphorz** [comment]
BTW, check out the new 5 patches which are in the "Demo Patches" folder. They are very good.
I've been listening to "shuffle.vcv" for the last hour while periodically tuning some knobs. A cross between middle east and bagpipes.

**Comment by nay-seven** [comment]
yes, will check them , thanks

**Comment by Strum** [comment]
@metaphorz Thanks for that, I've added it to the repo.

Glad you are enjoying the patches, I find myself doing the same thing with them. I'll put a patch together then listen to if for hours just tweaking things occasionally.

That it never repeats and is never predictable always keeps my ears interested.

I've been thinking of it like defining a chaotic attractor for the music which then stays close to the attractor but has no strictly repeating pattern. Like a lorentz fractal.

**Comment by metaphorz** [comment]
Yes, I agree on the fractal nature. On that topic, I am gearing up to make a bunch of modules similar to those I made in Max/Msp. They will support the construction of multiple equations, including difference and differential. For both of these, it would be useful if we had access to the past N samples based on the current rate. Assume the signal is s(t). It would be good to have s(t-Delta_T) with Delta_T = 1/SampleRate.

**Comment by envelopegen** [comment]
hey @metaphorz im trying to help contribute the the gui but im quite new at this... having trouble building... i've got Xcode, cmake, and home-brew installed... i keep running into "license file missing" or "plugin.mk: no such file *** no rules to make target" if you would share your process in making builds specifically for mental, I'd be happy to help you with future mac builds here. hope its not asking too much.

**Comment by metaphorz** [comment]
Someone named Zach Hendel sent a message from this thread but I do not see Zach's question here, and no private email was provided. The question was how to compile Strum's Mental Modules.  I used the process at the end of https://github.com/VCVRack/Rack. If you follow these instructions it should work.

**Comment by envelopegen** [comment]
i got a build working, but if its easy and you're comfortable doing a screen record when you build on mac for vcv 0.5 it would still be appreciated.

**Comment by Strum** [comment]
https://github.com/phdsg did the latest mac build.

**Comment by envelopegen** [comment]
awesome @phdsg

i'm looking for a tutorial to make the plugin.dylib on a mac so i could edit svg's and code all on same machine... i've followed the instructions in the vcv tutorial plugin and got that working but seem to be doing something wrong when I try to edit the terminal commands to point to mental's makefile.

there are a couple of video tutorials to make vcv on pc but not one on mac, i'm sure i'm not the only one who would like to learn... I was just suggesting I would in turn learn and contribute to future mac release builds if someone took the time to show this specifically for vcv, even better with mental as example, on a mac. Not expecting anyone to run out and set up a screen record software for this... just putting it out there in the ethos that this doesn't exist and would help.

**Comment by phdsg** [comment]
can't do screenrecording atm.
for the mac builds, i followed the [tutorial by Nik Jewell](http://nikjewell.net/vcvrack/setting_up.html) to set up the build environment and then followed the VCVRack instructions to build rack and the modules.
what were you trying to edit in the terminal and what was the error message?

**Comment by envelopegen** [comment]
got a development version (what I'm building against in the following issue) running thanks to that tutorial! now I'm running into this error while building the cartesian sequencer... I'm just doing (the 'main?' repository) 
git clone https://github.com/Strum/Strums_Mental_VCV_Modules.git   
is there a different repository (release?) I could use? or remove MentalCartesian.cpp before running build ? thanks for the help!
![screen shot 2017-12-05 at 2 33 45 pm](https://user-images.githubusercontent.com/33540835/33648516-235adbd8-da0f-11e7-8ddf-dbda100a270b.png)

**Comment by Strum** [comment]
removing the std:: before library function calls fixes the mac build issues.

at this point there is only the master branch, I'll still a noob with github.

**Comment by envelopegen** [comment]
so just remove these and ignore the other 'did you mean' stuff
![screen shot 2017-12-05 at 11 57 41 pm](https://user-images.githubusercontent.com/33540835/33650744-28b3179a-da18-11e7-89e5-956ab91db92c.png)

**Comment by Strum** [comment]
I don't have a mac to test on sorry.

you may have to look into the documentation to find out how to use the non standard implementation of C++ xcode uses.

**Comment by envelopegen** [comment]
it worked! hope I don't break it when i build my edits... thank you!

**Comment by Strum** [comment]
cool, if you break it just delete it a make a new clone.

**Comment by Strum** [comment]
@envelopegen 
@metaphorz 

Could either of you guys make a new Mac build for the repo please?

I've moved the releases into github and removed the old binaries to make the clone smaller, had a few people asking about Mac builds.

**Comment by metaphorz** [comment]
I am trying to clone right now. It is taking forever but my internet speed is 110Mbps so that isn't the problem.

**Comment by metaphorz** [comment]
I cannot upload the zip (> 10MB). Try this link: https://www.dropbox.com/sh/a33bxyxazd3qtsp/AABQYEUMn6iciNpn4iBA_SSRa?dl=0

**Comment by metaphorz** [comment]
Oops forget that. I was zipping the wrong directory:

[Strums_Mental_VCV_Modules.zip](https://github.com/Strum/Strums_Mental_VCV_Modules/files/1545967/Strums_Mental_VCV_Modules.zip)

**Comment by metaphorz** [comment]
I also just made a local modification to the readability of Counters after some FB discussion. I have to admit: the original colors make it very hard to see the counters. What are your thoughts on something like this?

![image](https://user-images.githubusercontent.com/3519631/33813544-1366baec-ddea-11e7-9456-9ee3b80e66b4.png)

**Comment by Strum** [comment]
@metaphorz Thanks, found someone to do the Mac build and have already put it up but thank's anyway.

Sorry but I'm not keen on your choice of colours for the counter, I like the original blue myself and have no problem with visibility with it, only one person has complained, so I've decided to leave it as is for now.

You are more than welcome to make your own custom look for the modules if you want though.

**Comment by metaphorz** [comment]
Sounds good - yes, aesthetics is a tricky area. As you say, user’s can change the color
schemes. In the future, maybe I’ll write some code that can change X modules automatically.
-p
