### ISSUE TITLE
issue: can't load strums mental plugin

### ISSUE THREAD

**Issue by robertocolabene** [Strum/Strums_Mental_VCV_Modules#21]
i'm on win 8.1 and rack doesn't wanna load the plugin anymore? what's happened?

**Comment by phdsg** [comment]
what rack version/plugin version are you using?
do you get any error messages or is the plugin just missing in rack's list?

**Comment by robertocolabene** [comment]
it just doesn't appear in the list 

version 0.5a
rack 0.5

edit: i tried again, now it's there... i think it was random bug don't know really
