### ISSUE TITLE
0.5b linux buid

### ISSUE THREAD

**Issue by phdsg** [Strum/Strums_Mental_VCV_Modules#27]
oops. doing it again.

**Comment by phdsg** [comment]
proper now.
[Strums_Mental_VCV_Modules_05b_linux.zip](https://github.com/Strum/Strums_Mental_VCV_Modules/files/1535179/Strums_Mental_VCV_Modules_05b_linux.zip)

**Comment by phdsg** [comment]
here is the new one:
sha256: e716ff6a9a98addc5eb07f92d8d524c627da5734375d97a084b8878a25b8f7c2
[mental-0.5.b-lin.zip](https://github.com/Strum/Strums_Mental_VCV_Modules/files/1693006/mental-0.5.b-lin.zip)

**Comment by Strum** [comment]
cheers.
