### ISSUE TITLE
built from source on Linux & MentalMasterClock can't find background SVG

### ISSUE THREAD

**Issue by Chaircrusher** [Strum/Strums_Mental_VCV_Modules#29]
The MentalMasterClock2.svg wasn't loading and the reason was it didn't exist!

Turns out MentalMasterClock.svg DOES exist so I copied it to MentalMasterClock2.svg and the jacks had labels again!

**Comment by Strum** [comment]
oops sorry, was testing another background and had forgotten to change it back
