### ISSUE TITLE
Does not supossed to be a MAC version too??

### ISSUE THREAD

**Issue by munropark** [Strum/Strums_Mental_VCV_Modules#30]
Only Linux and Windows listed
thank you

**Comment by Strum** [comment]
@munropark Sorry I don't have a Mac and have been relying on others to do the Mac builds, I hope to get a Mac build done in the next day or 2.

You could try building it yourself, it's not that hard , the instructions are on the Rack github.

**Comment by Strum** [comment]
mac build is up now

**Comment by munropark** [comment]
Thank you so much for your fast response!

**Comment by Strum** [comment]
no worries, enjoy.
