### ISSUE TITLE
Visual problems after V0.5.1 Update

### ISSUE THREAD

**Issue by doctorsaltds** [Strum/Strums_Mental_VCV_Modules#31]
<img width="601" alt="screen shot 2017-12-19 at 14 40 19" src="https://user-images.githubusercontent.com/3989994/34160033-a6ab3d54-e4cb-11e7-8753-b9ba3878c6b5.png">

**Comment by Strum** [comment]
what os?

**Comment by Strum** [comment]
@doctorsaltds  looks like the graphics for the sockets are missing.

**Comment by a1laserboy** [comment]
I have a similar issue but my sub mixer positions don't look as bad.

OSX 10.12.6, early 2015 13" MBP

![screen shot 2017-12-19 at 16 41 15](https://user-images.githubusercontent.com/13291547/34168282-05a9dd14-e4dc-11e7-87d9-0b15d15f91e9.png)

**Comment by Strum** [comment]
@a1laserboy I don't have a mac and have been getting others to do the mac builds but I can't test them.

I've changed a few of the layouts between .5a and .5b, patches made with older version might have cables in the wrong sockets or cables missing.

your picture looks right though.

**Comment by a1laserboy** [comment]
@Strum Looking at the readme.md, i'm on .5b (as downloaded by the new package manager). I placed these all in a patch today for the visual.

I've now installed everything I believe I need to be able to build, but so far haven't gotten around to learning how to do everything. Once I do, i'll be more than happy to test for you prior to you releasing.

**Comment by doctorsaltds** [comment]
I'm on OSX 10.12.6 , I first downloaded your plugs 2/3 weeks ago and today i used the new VCV plugin manager to update all my plugs and then this problem appeared . 
I tried to delete all your plug folder and re-install it but now they do not appear anymore in VCV .
And I got nothing about Mental plugs in the log.txt

**Comment by doctorsaltds** [comment]
it looks like the plugin manager downloaded your plugins in the wrong folder , I moved it in the good one and now I got this on the log.txt :
 
warning] Failed to load library /Users/blanchard/Documents/Rack/plugins/Strums_Mental_VCV_Modules-master/plugin.dylib: dlopen(/Users/blanchard/Documents/Rack/plugins/Strums_Mental_VCV_Modules-master/plugin.dylib, 2): image not found

they're still missing in vcv

**Comment by Strum** [comment]
@doctorsaltds, I haven't tried out the plugin manager yet, I may have to make some changes.

I don't have a Mac so I can't test the Mac builds, maybe that build is not compatible with your Mac version.

Have you tried building Rack and my plugin from source?

**Comment by Strum** [comment]
@a1laserboy, thanks, let me know how you get on, I'll try and get some work done on the manual.;

**Comment by doctorsaltds** [comment]
@Strum , No i didn't, I'm not skilled at coding but i'm gonna look around and start to learn the basics to do it .
Btw I can ask the community on VCV facebook page to help us on this point .

**Comment by Strum** [comment]
@doctorsaltds, i'm not on facebook , but i'm on the irc channel #VCVRack on freenode if you want to chat.

Building is easy, just follow the instructions.
