### ISSUE TITLE
Mental Modules dont show up in VCV for me please advise

### ISSUE THREAD

**Issue by userzxz** [Strum/Strums_Mental_VCV_Modules#33]
Dropped RAR in plugins folder, unzipped, opened VCV, modules not in plugin list, tried update still no go, any suggestions please (havent had this problem before)

**Comment by Coirt** [comment]
They would not show for me either then just noticed that the mental folder is not in its own folder. If you are on Windows navigate to MyDocuments/Rack/plugins and make a new folder there called "mental" find the files in the plugins folder:

![mental](https://user-images.githubusercontent.com/12150421/35406577-2b910d94-0201-11e8-9373-4d5726dda6b0.JPG)

cut and paste or move these into the mental folder you created.
