### ISSUE TITLE
Plugin Manager

### ISSUE THREAD

**Issue by ghost** [Strum/Strums_Mental_VCV_Modules#34]
Hi!

First of all sry that you didnt get any svg files from me for your modules. I was totally busy and forgot about it... but I saw that someone else took on the job and helped you.

I m writting you also because of the plugin manager. you didnt provide any download links for your current version in the community repo.. 
before you can send a PR with the downloadlinks, please make sure that your makefile includes the correct SLUG and VERSION number of your latest build. You can have a look at the tutorial makefile if you want to know how to do that ;) 

the json file also got a VERSION number which needs to be edit aswell if the version you will send is newer than the current in the json file.

https://github.com/VCVRack/Tutorial/blob/master/Makefile

**Comment by Strum** [comment]
@Phal-anx 

Yeah sorry I've not been focused on Rack the last couple of months, getting back into it now.

I think the community thing has been scrapped for the meantime hasn't it? so I don't think this matters anymore.

I got some help with the graphics but I liked the look you had going much more.

If you've got time I'd appreciate you sending me what you've done and maybe I can use it as templates to do the rest myself.
