### ISSUE TITLE
0.5b Windows Not showing up

### ISSUE THREAD

**Issue by Coirt** [Strum/Strums_Mental_VCV_Modules#35]
There is no mental folder inside the zip for 0.5b. Modules do not show in VCV when you unzip. 

Easy fix create new folder copy from zip paste in new folder rename folder to "mental"

**Comment by Totti111** [comment]
It doesent work for me. The plugin.dll file is missing in the download. Is the plugin.dll needed ??

**Comment by Coirt** [comment]
yes.

**Comment by Totti111** [comment]
Is it possible to download the plugin.dll file sepretaly? It is missing everytime i download the Zip file.

**Comment by Coirt** [comment]
[mental.zip](https://github.com/Strum/Strums_Mental_VCV_Modules/files/1679887/mental.zip)

**Comment by Strum** [comment]
Sorry guys., I've not been focused on rack at all the last couple of months.

Looks like you sorted this issue out yourselves anyway, well done.

Next release I make I'll make sure it unzips into the right directories.

Hopefully in the next few days.
