### ISSUE TITLE
std::div_t

### ISSUE THREAD

**Issue by EO2** [Strum/Strums_Mental_VCV_Modules#37]
Hi,

Building on osx, I had to remove the 'std::' prefix from two lines (like this error message suggested).

Thanks for nice modules! :)

make
c++  -fPIC -I../../include -I../../dep/include -DSLUG=mental -DVERSION=0.5.b -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7  -std=c++11 -stdlib=libc++ -c -o build/src/MentalCartesian.cpp.o src/MentalCartesian.cpp
src/MentalCartesian.cpp:156:5: error: no type named 'div_t' in namespace 'std';
      did you mean simply 'div_t'?
    std::div_t division_x;
    ^~~~~~~~~~
    div_t
/usr/include/stdlib.h:85:3: note: 'div_t' declared here
} div_t;
  ^
src/MentalCartesian.cpp:166:16: error: use of undeclared identifier
      'division_y'; did you mean 'division_x'?
    std::div_t division_y;
               ^~~~~~~~~~
               division_x
src/MentalCartesian.cpp:156:16: note: 'division_x' declared here
    std::div_t division_x;
               ^
src/MentalCartesian.cpp:166:15: error: expected ';' after expression
    std::div_t division_y;
              ^
              ;
src/MentalCartesian.cpp:166:10: error: no member named 'div_t' in namespace
      'std'
    std::div_t division_y;
    ~~~~~^
src/MentalCartesian.cpp:167:5: error: use of undeclared identifier 'division_y';
      did you mean 'division_x'?
    division_y = div(y_position + y_cv,4);
    ^~~~~~~~~~
    division_x
src/MentalCartesian.cpp:156:16: note: 'division_x' declared here
    std::div_t division_x;
               ^
src/MentalCartesian.cpp:170:18: error: use of undeclared identifier 'division_y'
    y_position = division_y.rem;
                 ^
6 errors generated.
make: *** [build/src/MentalCartesian.cpp.o] Error 1

**Comment by Strum** [comment]
@EO2 

Sorry it's taken me a bit to get back to you.

yes I'm aware of this issue, it's a Mac specific thing, I'll try and modify the code so  it builds on mac in the next week or so.

Does the binary release work?

**Comment by EO2** [comment]
Just tested them, and they do work.
Did not see the VCV link to binaries before now, hehe.

A good opportunity to make my first pull request : )

**Comment by EO2** [comment]
My bad!
There was a whitespace in Rack path, and some libs not loaded.
built again, and check that 'make dep' has no errors.

Thanks!
