### ISSUE TITLE
Mixer - Needs a bit of an explanation? 

### ISSUE THREAD

**Issue by JeffGreenlee42** [Strum/Strums_Mental_VCV_Modules#39]
I had seen an Youtube video "Modular curiosity"  https://www.youtube.com/watch?v=CZIqGavz-Qk  that features the Mental Mixer.  In the video I noticed you had direct PAN controls on the right side of the mixer.  I notice that at some point PAN had been removed - (I presume that part has been moved into MIX bus?). After some experimenting I can see that pan can still be achieved by patching the same signal to multiple rows... but there is no documentation on this.  Maybe a bit of an explanation of how to  pan within this module might make it more clear (or at least how to use in conjunction with SubMix module?

**Comment by Strum** [comment]
Yeah sorry bout that, changed the background graphic and haven't added the labels back in.

Also been very slack with the documentation. sorry again.

Ok so sockets are colour coded.
audio inputs purple 
audio outputs red
cv inputs dark green
cv outputs light green
gate inputs orange
gate outputs yellow.

the mixer channels from the top down are as follows
audio in
level knob
level CV in
pan knob
pan cv in
aux send 1
aux send 2
channel mute switch
mute gate input.

let me know how you get on.

**Comment by JeffGreenlee42** [comment]
Awesome!  Just your little write up makes it a lot easier to grasp.  I must have had something wrong happening in Rack.. the pan knob was not working last night..  Now it is. ! 

 By the way,  I am just a dabbler in Github,  so I am never completely clear how this all works... but in any case,  If there is something that I could assist with, like documentation or relatively simple tasks...  (if that's possible) let me know.  :)   I'm sort of looking for something to do. 

I am curious:  I can see why the labeling might be a bit of a challenge,  You have made this module nice and compact, (for a 12 channel mixer!)  but getting adding labels that are legible looks challenging!  Do you plan to just add a column on one of the side of the columns with labels? 

Since I was not aware of the significance of the color coding,  I had thought the second row was audio input...  Funny what you find when experimenting!  Have you noticed that if you do put a second audio in to that second row CV Input,  it has a dramatic effect on the original Audio?  kind of an interesting feature!

**Comment by Strum** [comment]
Part of my original design concept was to keep the modules as small as possible, @phdsg has made a few alternate backgrounds that are even smaller than my originals but don't have the text labels yet, the earlier version of the mixer did have a column of text labels on the left, i'll add it beck for the 06 release coming in a few weeks.

The CV level control is effectively a simple VCA. Applying an audio rate signal there is likely to produce interesting but not necessarily musical results.

**Comment by JeffGreenlee42** [comment]
Also,  I sort of get the two send/return functions at the top,  I can see one is send,  one is return.. I thought the 3rd input was a CV but according to your color scheme its also an audio input.  Can you describe what it's for? Stereo return?

**Comment by Strum** [comment]
yeah, mono sends, stereo returns

**Comment by Strum** [comment]
If you would like to help, what I really need is someone who is good with GUI design to do better skins.

any feedback is also helpful and i'd be interested to see how you are using them and hear the results.

Have you looked at the demo patches? they might give you some clues as to how they work as well.

**Comment by JeffGreenlee42** [comment]
Yes, I'm going to take a look at those demos. I think I need to make
another go at setting up a development environment on my PC for Rack.  Last
time I tried to do it .. following the provided instructions..  I could not
get it to work.So I confess I am feeling intimidated by this development
environment.    I am curious What the mechanism is for adding labels.  I
assume there is a Rack label object that defines position, text, font and
size?

Nevertheless,  if you want my feedback.. at least for the Mental Mixer,  I
would suggest that you add a 13th row on the left with labels that align
with each row.  and seeing that there is empty space at the top, I would
move the two Return sets to the right and then add a clear diagram in a
similar configuration ...something really simple.. Even just single letters
like "R" and "L "out"  would make it more intuitive at first glance.


Jeff Greenlee

"Music is Love in search of a voice."
Leo Tolstoy

**Comment by Strum** [comment]
@JeffGreenlee42 

The current state of the mixer doesn't have the labels, the previous version did.

I currently redesigning the backgrounds and will add labels back to the ones that currently don't have them.

Now that Rack has zoom the need to keep them small isn't so great so I think I'll make them a bit bigger to allow more space for labels and diagrams.

The labels are in the background .svg files generally but you can also make in them in the module code.
it was something I had been meaning to experiment with but I've been distracted with other things.

**Comment by JeffGreenlee42** [comment]
Ok,  Thanks for the feedback!   I find myself using your mixer a lot!  I
like it because its quite compact.. and straightforward!  I sometimes use
the VCV Console,  but yours takes up a third of the space!!! :)


Jeff Greenlee

"Music is Love in search of a voice."
Leo Tolstoy

**Comment by Strum** [comment]
@JeffGreenlee42 

When I made the mixer there wasn't another stereo multi channel mixer available so I wrote it, and the other modules, for my own use and didn't put much into the UI design because i understood how they worked, I didn't expect that as many people would use them as have or that others would take my code and make better UIs for them.

Rack is a really cool project and a cool bunch of people.

**Comment by grinsted** [comment]
I like your mixer as it is compact, but still has fx send&return. I've modified the svg's a bit for my own rack. It is not super precisely aligned, but i think by just grouping them then it is already a lot easier to figure out. 

I added a pull request with some styling. #42
