### ISSUE TITLE
Merge issues with latest commit

### ISSUE THREAD

**Issue by cschol** [Strum/Strums_Mental_VCV_Modules#40]
@Strum Looks like, your last commit changing the backgrounds has a ton of merge issues:

https://github.com/Strum/Strums_Mental_VCV_Modules/commit/67fd00ff1d7251951825cfc5ede53d09621a72f1

![strum_merge_issues](https://user-images.githubusercontent.com/624427/37556713-6964a0dc-29bf-11e8-8b80-1cd3f7fb9983.png)

**Comment by Strum** [comment]
yeah sorry, I messed something up with git and it merged the changes instead of overwriting the old files.

bugger

will copy the old ones back over.

**Comment by cschol** [comment]
Great, thank you!

**Comment by cschol** [comment]
Please let me know when this is completed in the Rack Repair Thread. Thanks!

**Comment by Strum** [comment]
@cschol 
yeah, sorry , been busy with other things.
will sort out today.

**Comment by Strum** [comment]
@cschol 

I think it's fixed now.

**Comment by cschol** [comment]
Perfect. Works great. Thank you!
