### ISSUE TITLE
Mental Modules 6.1?  can't find them on VCVrack plugins page

### ISSUE THREAD

**Issue by JeffGreenlee42** [Strum/Strums_Mental_VCV_Modules#41]
I presume you have updated modules?  They show the version on the VCVRack plugins page as 6.1.  But there are no links to download and no way to run update.  Are they in an undisclosed location?    If they are still under development,  you might want to make an announcement on the VCVRack Facebook page. 

Cheers

**Comment by Strum** [comment]
@JeffGreenlee42 

Sorry it's taken a while to get back to you, modules are up on the community plugin page now and can be installed from there, but if you wait a few days I'll have the new version up with the new better UI look and labels on the mixer, or you can pull the code and build it yourself.

Must have been a glitch during the changeover process and you must have looked at a time when they weren't up yet. I've been in touch with the community team and they hadn't asked me to do anything.

Cheers.
