### ISSUE TITLE
Migrate to Rack v1?

### ISSUE THREAD

**Issue by omni72** [Strum/Strums_Mental_VCV_Modules#44]
Hello! ;) 

Just checking in to see if there was already an effort underway to migrate your suite of modules to Rack v1? If not perhaps the VCV community can take on the task of migrating?

Thanks & take care

**Comment by Strum** [comment]
Thanks,
       I've been busy with other things recently and haven't had a chance to update the code yet, It might be a few weeks yet before I can get to it so if you know someone that wants to do it I'd be happy for them to.

My computer is getting old and slow and I'm having trouble even running rack without glitches all the time at the moment which has stalled my work with it unfortunately

Thanks again for your message.

Strum

**Comment by omni72** [comment]
Hi Strum - Thanks so much for getting back to me so quickly! :) I have posted this to the VCV forum and hopefully someone will indeed feel like running with the migration.

Sorry to hear about the technical struggles. That would definitely make it difficult to update the modules! 

Take care

**Comment by Strum** [comment]
No worries, I'm a bit surprised anyone is still using the modules as they have mostly been superseded by others now, I'll try to get my head around updating the code in the next few weeks once my schedule clears up a bit.

I've been having trouble since the 0.6 release , i've tried everything I can think of, it might be an audio interface driver issue but as i said this computer is getting old and slow and i really need to upgrade.

Thanks for your interest again.

Cheers.

**Comment by omni72** [comment]
Hi Strum! Thanks for touching base on the modules. I'm a complete and total newb to the VCV scene soooooooo I don't always know what the current faves are or what has been essentially replaced by other modules :D Plus it's kind of cool to get to see & play with different people's ideas of how to solve a particular problem.

Sounds like you've now got justification to upgrade your hardware right? :D 

Yvw any time. Thanks for sharing your modules with the community!

Take care

**Comment by CommanderAsdasd** [comment]
Your Cartesian Sequencer is adorable, and inspired me to working on my own :3
Also, there is many other simple but very handy tools, as your conunters and mixers

**Comment by Strum** [comment]
@CommanderAsdasd , Thank you, I never got the cartesian working as i had originally intended, some of the control inputs were unpredictable and there were other features I had planned to add. I'd be interested to see what you have done with it and it's great that you have been inspired to get into coding your own modules. 

Simple but useful modules was my original intention and for the generative music I'm interested in you need utilities as much or more than oscillators and filters. 

Thanks again.

Strum

**Comment by gilbertohasnofb** [comment]
I also would be interested in a v1.0 release.

**Comment by mocmichal** [comment]
So will your modules be available for download using Plugin Library as well ?
Thank you for your work, I (as well as others) am glad that for example Matrix is back! <3

**Comment by Strum** [comment]
Yes, I just have to submit them to the library team and they put them up, 
was planning on doing that today, they should be up in a few days. 

mocmichal writes:
