### ISSUE TITLE
I'm sorry, I thought your were the one responsible for the MindMeld Mixer for VC Rack

### ISSUE THREAD

**Issue by mikeloveridge** [Strum/Strums_Mental_VCV_Modules#50]
I seem to have gotten things confused.  I submitted issues and requests to the wrong developer.  I honestly don't know how this happened.  I don't know how to access your email to inform you of my mistake so I'm just submitting another issue.
Sorry, Mike

**Comment by Strum** [comment]
No worries, i thought that was what had happened.
Did you find the guy you were after?
