### ISSUE TITLE
Back compatibility with pre-V1.0 patches?

### ISSUE THREAD

**Issue by luposapien** [Strum/Strums_Mental_VCV_Modules#53]
Is it possible to open an old patch that used pre-V1.0 Mental modules, and have it pull in the new versions? I used your Quad LFO and Mults modules quite frequently prior to the V1 update, and a good majority of my old patches now have significant holes in them. Was very excited to see your update posted in the plugin manager, but then realized that Rack didn't recognize the new modules as being the same as the old ones. Any help/pointers you can offer would be greatly appreciated

Sorry for what may be a very basic question, but I have no coding experience, and haven't had any luck finding an answer by searching around.

Many thanks.

**Comment by Strum** [comment]
Sorry, I have had the same problem, though I have not changed positions or names  of controls they seemed to have been remapped somehow in the upgrade and no longer wire up the same way they did before.
This has happened in previous updates, I gave up trying to keep patches between versions after 0.6. 
Out of my hands I'm afraid.
