### ISSUE TITLE
 Keep as one plugin or break into separate plugins?

### ISSUE THREAD

**Issue by Strum** [Strum/Strums_Mental_VCV_Modules#6]
I have been thinking about splitting up the modules into more than one plugin.

Maybe one plugin for utilities and another for pitch related modules.

What do people think?, it's not really a big issue but Id be interested to know what people think about the idea.

**Comment by cbrpnk** [comment]
I don't have any issues with the way it is right now. So 1 vote for "leave it like that".

**Comment by Strum** [comment]
ok that advantage of splitting it up would be that older modules would be stable while modules in development would be in a separate plugin.

i'm still undecided, but don't think it's a major issue, 1 vote for all in one so far. see what others say.

**Comment by mikeloveridge** [comment]
Just sent an enhancement request as a separate item.  My suggestion is to keep it separate, but make it full width so it can go above the mixer allowing the Aux channels to line up with the mixer below.  Keep the labels on both. :)
