### ISSUE TITLE
Mac Binary not working?

### ISSUE THREAD

**Issue by jamesbernard** [Strum/Strums_Mental_VCV_Modules#8]
Unzipped.. created a folder and put the plugin.dylib file in it. Nothing. Anyone get this working yet on Mac?

**Comment by ghost** [comment]
Hi,
I think it's not working as it was built against the latest dev branch. 

Try this one!

[Strums_Mental_VCV_Modules_Mac_0.4.0.zip](https://github.com/Strum/Strums_Mental_VCV_Modules/files/1404495/Strums_Mental_VCV_Modules_Mac_0.4.0.zip)

**Comment by Strum** [comment]
@jamesbernard , i don't have a mac and am relying on others to do the mac builds and I can't test them.

@charlescrammond , thanks heaps for sorting this out. I'll add the file to the releases tonight, though I've made a new module which will lead to 2 more similar ones easily so it'll need to be rebuilt in the next day or 2 anyway.

**Comment by jamesbernard** [comment]
Works great! THANK YOU!!!!

**Comment by nay-seven** [comment]
Hello, Thanks a lot for these ones !, here on yosemite ( will test later on Sierra) some captions looks not really the good place ?
![mental](https://user-images.githubusercontent.com/13808201/31861268-8e63c8ca-b72a-11e7-9e85-7681da07588d.png)

**Comment by Strum** [comment]
New graphics are in the works, look like one of the background svg files is missing, i might have forgotten to add it to the repo. sorry.

Yes some of the text doesn't line up i've just been busy dealing with getting the functionality work first, should all be sorted with the new look hopefully this week.

**Comment by nay-seven** [comment]
great, thanks !

**Comment by Strum** [comment]
Uploaded the missing .svg just now.
